export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_SUCCESS="SINGLE_PRODUCT_SUCCESS";

export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_FAILURE="AUTH_FAILURE"
export const AUTH_ALL_USER_DATA=" AUTH_ALL_USER_DATA"
export const AUTH_LOGOUT_SUCCESS="AUTH_LOGOUT_SUCCESS"
export const AUTH_ADD_NEW_USER_DATA="AUTH_ADD_NEW_USER_DATA"
export const ADMIN_CHECK="ADMIN_CHECK"

export const ADD_CART_PRODUCT_SUCCESS="ADD_CART_PRODUCT_SUCCESS"

export const USER_REQUEST="USER_REQUEST";
export const USER_FAILURE="USER_FAILURE";
export const USER_SUCCESS="USER_SUCCESS";
export const SINGLE_USER_SUCCESS="SINGLE_USER_SUCCESS";


export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_LOADING="GET_USER_LOADING";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const PATCH_USER = "PATCH_USER";
export const DELETE_USER = "DELETE_USER";

export const GET_SINGLE_USER_SUCCESS="GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_REQUEST="GET_SINGLE_USER_REQUEST";
export const GET_SINGLE_USER_FAILURE="GET_SINGLE_USER_FAILURE";

export const DELETE_SINGLE_USER_REQUEST = 'DELETE_SINGLE_USER_REQUEST';
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS';
export const DELETE_SINGLE_USER_FAILURE = 'DELETE_SINGLE_USER_FAILURE';

export const GET_PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const GET_PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

export const PATCH_PRODUCT = "PATCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
